default: &default
  adapter: postgresql
  pool: 5
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_URL'] %>
  timeout: 5000

development:
  <<: *default
  database: chrome-extention-test

production: 
  url: <%= ENV['DATABASE_URL'] %>